services:
  - type: web
    name: telegram-quiz-scraper
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: telegram_quiz_bot
